### ISSUE TITLE
Добавить hardware-USB взамен "нарисованного"

### ISSUE THREAD

**Issue by Valber** [uISP/uisp-schematics#1]
Внешне хоть и выглядит задумка с USB рисунком на плате интересно, но либо контакта не происходит, либо выпадает.

**Comment by nekromant** [comment]
Валбер, я дизайн переделывать и перезаказывать uISP ближайшее время не планирую. Не до того сейчас. Следующая итерация, если и будет - то будет с STM32 и там уже будет и USB и microusb

**Comment by spacemonkeydelivers** [comment]
Я бы это обозвал proposal'ами, которые нужно выполнить, чтобы запилить успешный проект.
Мне кажется, имеет смысл обсуждать замену интерфейса с учетом предполагаемого корпуса для устройства.
Вариант с микро-усб выглядит неплохо.

**Comment by Valber** [comment]
я бы оставил оба устройства в модельном ряде, про корзинку аргументы убедили. Но модель с AVR-кой я бы оставил, под неё и прогать проще.

uISP-lite
uISP-elite
