### ISSUE TITLE
Добавить корзинку для MLF-package Atmega8

### ISSUE THREAD

**Issue by Valber** [uISP/uisp-schematics#2]
Так как инструмент будет часто переписываться, то стоит дать пользователю возможность удалить сгоревший камень.

**Comment by nekromant** [comment]
Не имеет смысла. У тебя  гарантированно 100к перезаписей. Я даже 1к не заюзал на самом древнем uISP на котором отлаживал большую часть того, что есть в репозитории uISP.
К тому же она стоит около 30$, так что lowcost преимущество теряется.

**Comment by spacemonkeydelivers** [comment]
В качестве возможного фич-реквеста: может быть в новой версии уиспа стоит предусмотреть флешку, в которой будут храниться прошивки, а софт будет выбирать, какую из них использовать.
Соответственно потребуется меньше перезаписей.

**Comment by nekromant** [comment]
На AVR не вариант, так как префетча из внешней флеши нет. Если юзать то STM32F103RET6, у которого 512к флеша, компилить проши с -fPIC и выбирать какую юзать.

**Comment by Valber** [comment]
SMD мы справимся с дуиной и внешнем носителем аля комп или дроидфон
